#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#  jpa:
#    show-sql: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unmdp_unmdp
    username: root
    password: leonel127
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      ddl-auto: create-drop
    #ddl-auto: none

